// ─────────────────────────────────────────────────────────────────────────────
// Вбудована бібліотека зображень
//
// ЯК ДОДАТИ СВОЄ ЗОБРАЖЕННЯ:
//   1. Скопіюйте файл до  public/library/  (наприклад: public/library/logo.png)
//   2. Додайте рядок у потрібну категорію нижче:
//        { name: 'Назва', src: '/library/logo.png' }
//   3. Збережіть — зображення одразу з'явиться в бібліотеці (Vite HMR).
//
// Підтримуються: PNG, JPG, SVG, WebP, GIF
// ─────────────────────────────────────────────────────────────────────────────

export const LIBRARY = [
  {
    id: 'banners',
    label: 'Фони',
    items: [
      { name: 'Банер 1', src: '/library/banner/baner1.png' },
      { name: 'Банер 2', src: '/library/banner/baner2.png' },
      { name: 'Банер 3', src: '/library/banner/baner3.png' },
      { name: 'Банер 4', src: '/library/banner/baner4.png' },
      { name: 'Банер 5', src: '/library/banner/baner5.png' },
      { name: 'Банер 6', src: '/library/banner/baner6.png' },
      { name: 'Банер 7', src: '/library/banner/baner7.png' },
      { name: 'Банер 8', src: '/library/banner/baner8.png' },
      { name: 'Банер 9', src: '/library/banner/baner9.png' },
      { name: 'Банер 10', src: '/library/banner/baner10.png' },
    ],
  },
  {
    id: 'bubbles',
    label: 'Бульбашки',
    items: [
      { name: 'Бульбашка 1', src: '/library/bubble/bubble.png' },
      { name: 'Бульбашка 2', src: '/library/bubble/bubble2.png' },
      { name: 'Бульбашка 3', src: '/library/bubble/bubble3.png' },
      { name: 'Бульбашка 4', src: '/library/bubble/bubble4.png' },
      { name: 'Бульбашка 5', src: '/library/bubble/bubble5.png' },
      { name: 'Бульбашка 6', src: '/library/bubble/bubble6.png' },
      { name: 'Бульбашка 7', src: '/library/bubble/bubble7.png' },
      { name: 'Бульбашка 8', src: '/library/bubble/bubble8.png' },
      { name: 'Бульбашка 9', src: '/library/bubble/bubble9.png' },
      { name: 'Бульбашка 10', src: '/library/bubble/bubble10.png' },
      { name: 'Бульбашка 11', src: '/library/bubble/bubble11.png' },
      { name: 'Бульбашка 12', src: '/library/bubble/bubble12.png' },
      { name: 'Бульбашка 13', src: '/library/bubble/bubble13.png' },
      { name: 'Бульбашка 14', src: '/library/bubble/bubble14.png' },
      { name: 'Бульбашка 15', src: '/library/bubble/bubble15.png' },
      { name: 'Бульбашка 16', src: '/library/bubble/bubble16.png' },
      { name: 'Бульбашка 17', src: '/library/bubble/bubble17.png' },
      { name: 'Бульбашка 18', src: '/library/bubble/bubble18.png' },
      { name: 'Бульбашка 19', src: '/library/bubble/bubble19.png' },
      { name: 'Бульбашка 20', src: '/library/bubble/bubble20.png' },
      { name: 'Бульбашка 21', src: '/library/bubble/bubble21.png' },
      { name: 'Бульбашка 22', src: '/library/bubble/bubble22.png' },
      { name: 'Бульбашка 23', src: '/library/bubble/bubble23.png' },
      { name: 'Бульбашка 24', src: '/library/bubble/bubble24.png' },
      { name: 'Бульбашка 25', src: '/library/bubble/bubble25.png' },
      { name: 'Бульбашка 26', src: '/library/bubble/bubble26.png' },
      { name: 'Бульбашка 27', src: '/library/bubble/bubble27.png' },
      { name: 'Бульбашка 28', src: '/library/bubble/bubble28.png' },
      { name: 'Бульбашка 29', src: '/library/bubble/bubble29.png' },
      { name: 'Бульбашка 30', src: '/library/bubble/bubble30.png' },
      { name: 'Бульбашка 31', src: '/library/bubble/bubble31.png' },
      { name: 'Бульбашка 32', src: '/library/bubble/bubble32.png' },
      { name: 'Бульбашка 33', src: '/library/bubble/bubble33.png' },
      { name: 'Бульбашка 34', src: '/library/bubble/bubble34.png' },
      { name: 'Бульбашка 35', src: '/library/bubble/bubble35.png' },
      { name: 'Бульбашка 36', src: '/library/bubble/bubble36.png' },
      { name: 'Бульбашка 37', src: '/library/bubble/bubble37.png' },
      { name: 'Бульбашка 38', src: '/library/bubble/bubble38.png' },
      { name: 'Бульбашка 39', src: '/library/bubble/bubble39.png' },
      { name: 'Бульбашка 40', src: '/library/bubble/bubble40.png' },
      { name: 'Бульбашка 41', src: '/library/bubble/bubble41.png' },
      { name: 'Бульбашка 42', src: '/library/bubble/bubble42.png' },
      { name: 'Бульбашка 43', src: '/library/bubble/bubble43.png' },
    ],
  },
  {
    id: 'devices',
    label: 'Девайси',
    items: [
      { name: 'Девайс 1', src: '/library/device/device1.png' },
      { name: 'Девайс 2', src: '/library/device/device2.png' },
      { name: 'Девайс 3', src: '/library/device/device3.png' },
      { name: 'Девайс 4', src: '/library/device/device4.png' },
      { name: 'Девайс 5', src: '/library/device/device5.png' },
      { name: 'Девайс 6', src: '/library/device/device6.png' },
      { name: 'Девайс 7', src: '/library/device/device7.png' },
      { name: 'Девайс 8', src: '/library/device/device8.png' },
      { name: 'Девайс 9', src: '/library/device/device9.png' },
      { name: 'Девайс 10', src: '/library/device/device10.png' },
      { name: 'Девайс 11', src: '/library/device/device11.png' },
      { name: 'Девайс 12', src: '/library/device/device12.png' },
      { name: 'Девайс 13', src: '/library/device/device13.png' },
      { name: 'Девайс 14', src: '/library/device/device14.png' },
      { name: 'Девайс 15', src: '/library/device/device15.png' },
      { name: 'Девайс 16', src: '/library/device/device16.png' },
      { name: 'Девайс 17', src: '/library/device/device17.png' },
      { name: 'Девайс 18', src: '/library/device/device18.png' },
      { name: 'Девайс 19', src: '/library/device/device19.png' },
      { name: 'Девайс 20', src: '/library/device/device20.png' },
      { name: 'Девайс 21', src: '/library/device/device21.png' },
      { name: 'Девайс 22', src: '/library/device/device22.png' },
      { name: 'Девайс 23', src: '/library/device/device23.png' },
      { name: 'Девайс 24', src: '/library/device/device24.png' },
      { name: 'Девайс 25', src: '/library/device/device25.png' },
      { name: 'Девайс 26', src: '/library/device/device26.png' },
      { name: 'Девайс 27', src: '/library/device/device27.png' },
      { name: 'Девайс 28', src: '/library/device/device28.png' },
      { name: 'Девайс 29', src: '/library/device/device29.png' },
      { name: 'Девайс 30', src: '/library/device/device30.png' },
      { name: 'Девайс 31', src: '/library/device/device31.png' },
      { name: 'Девайс 32', src: '/library/device/device32.png' },
      { name: 'Девайс 33', src: '/library/device/device33.png' },
      { name: 'Девайс 34', src: '/library/device/device34.png' },
      { name: 'Девайс 35', src: '/library/device/device35.png' },
      { name: 'Девайс 36', src: '/library/device/device36.png' },
      { name: 'Девайс 37', src: '/library/device/device37.png' },
      { name: 'Девайс 38', src: '/library/device/device38.png' },
      { name: 'Девайс 39', src: '/library/device/device39.png' },
      { name: 'Девайс 40', src: '/library/device/device40.png' },
      { name: 'Девайс 41', src: '/library/device/device41.png' },
      { name: 'Девайс 42', src: '/library/device/device42.png' },
      { name: 'Девайс 43', src: '/library/device/device43.png' },
      { name: 'Девайс 44', src: '/library/device/device44.png' },
      { name: 'Девайс 45', src: '/library/device/device45.png' },
      { name: 'Девайс 46', src: '/library/device/device46.png' },
      { name: 'Девайс 47', src: '/library/device/device47.png' },
      { name: 'Девайс 48', src: '/library/device/device48.png' },
      { name: 'Девайс 49', src: '/library/device/device49.png' },
      { name: 'Девайс 50', src: '/library/device/device50.png' },
      { name: 'Девайс 51', src: '/library/device/device51.png' },
      { name: 'Девайс 52', src: '/library/device/device52.png' },
      { name: 'Девайс 53', src: '/library/device/device53.png' },
      { name: 'Девайс 54', src: '/library/device/device54.png' },
      { name: 'Девайс 55', src: '/library/device/device55.png' },
      { name: 'Девайс 56', src: '/library/device/device56.png' },
      { name: 'Девайс 57', src: '/library/device/device57.png' },
      { name: 'Девайс 58', src: '/library/device/device58.png' },
      { name: 'Девайс 59', src: '/library/device/device59.png' },
      { name: 'Девайс 60', src: '/library/device/device60.png' },
      { name: 'Девайс 61', src: '/library/device/device61.png' },
      { name: 'Девайс 62', src: '/library/device/device62.png' },
      { name: 'Девайс 63', src: '/library/device/device63.png' },
      { name: 'Девайс 64', src: '/library/device/device64.png' },
      { name: 'Девайс 65', src: '/library/device/device65.png' },
      { name: 'Девайс 66', src: '/library/device/device66.png' },
      { name: 'Девайс 67', src: '/library/device/device67.png' },
      { name: 'Девайс 68', src: '/library/device/device68.png' },
      { name: 'Девайс 69', src: '/library/device/device69.png' },
      { name: 'Девайс 70', src: '/library/device/device70.png' },
      { name: 'Девайс 71', src: '/library/device/device71.png' },
      { name: 'Девайс 72', src: '/library/device/device72.png' },
      { name: 'Девайс 73', src: '/library/device/device73.png' },
      { name: 'Девайс 74', src: '/library/device/device74.png' },
      { name: 'Девайс 75', src: '/library/device/device75.png' },
      { name: 'Девайс 76', src: '/library/device/device76.png' },
      { name: 'Девайс 77', src: '/library/device/device77.png' },
      { name: 'Девайс 78', src: '/library/device/device78.png' },
      { name: 'Девайс 79', src: '/library/device/device79.png' },
      { name: 'Девайс 80', src: '/library/device/device80.png' },
      { name: 'Девайс 81', src: '/library/device/device81.png' },
      { name: 'Девайс 82', src: '/library/device/device82.png' },
      { name: 'Девайс 83', src: '/library/device/device83.png' },
      { name: 'Девайс 84', src: '/library/device/device84.png' },
      { name: 'Девайс 85', src: '/library/device/device85.png' },
      { name: 'Девайс 86', src: '/library/device/device86.png' },
      { name: 'Девайс 87', src: '/library/device/device87.png' },
      { name: 'Девайс 88', src: '/library/device/device88.png' },
      { name: 'Девайс 89', src: '/library/device/device89.png' },
      { name: 'Девайс 90', src: '/library/device/device90.png' },
      { name: 'Девайс 91', src: '/library/device/device91.png' },
      { name: 'Девайс 92', src: '/library/device/device92.png' },
      { name: 'Девайс 93', src: '/library/device/device93.png' },
    ],
  },
  {
    id: 'clear_devices',
    label: 'Чисті девайси',
    items: [
      { name: 'Чистий девайс 1', src: '/library/clear_device/device_clear1.png' },
      { name: 'Чистий девайс 2', src: '/library/clear_device/device_clear2.png' },
      { name: 'Чистий девайс 3', src: '/library/clear_device/device_clear3.png' },
      { name: 'Чистий девайс 4', src: '/library/clear_device/device_clear4.png' },
      { name: 'Чистий девайс 5', src: '/library/clear_device/device_clear5.png' },
      { name: 'Чистий девайс 6', src: '/library/clear_device/device_clear6.png' },
      { name: 'Чистий девайс 7', src: '/library/clear_device/device_clear7.png' },
      { name: 'Чистий девайс 8', src: '/library/clear_device/device_clear8.png' },
      { name: 'Чистий девайс 9', src: '/library/clear_device/device_clear9.png' },
      { name: 'Чистий девайс 10', src: '/library/clear_device/device_clear10.png' },
      { name: 'Чистий девайс 11', src: '/library/clear_device/device_clear11.png' },
      { name: 'Чистий девайс 12', src: '/library/clear_device/device_clear12.png' },
      { name: 'Чистий девайс 13', src: '/library/clear_device/device_clear13.png' },
      { name: 'Чистий девайс 14', src: '/library/clear_device/device_clear14.png' },
      { name: 'Чистий девайс 15', src: '/library/clear_device/device_clear15.png' },
      { name: 'Чистий девайс 16', src: '/library/clear_device/device_clear16.png' },
      { name: 'Чистий девайс 17', src: '/library/clear_device/device_clear17.png' },
      { name: 'Чистий девайс 18', src: '/library/clear_device/device_clear18.png' },
    ],
  },
  {
    id: 'sale_devices',
    label: 'Девайси знижок',
    items: [
      { name: 'Знижка 1', src: '/library/sale/sale1.png' },
      { name: 'Знижка 2', src: '/library/sale/sale2.png' },
      { name: 'Знижка 3', src: '/library/sale/sale3.png' },
      { name: 'Знижка 4', src: '/library/sale/sale4.png' },
      { name: 'Знижка 5', src: '/library/sale/sale5.png' },
      { name: 'Знижка 6', src: '/library/sale/sale6.png' },
      { name: 'Знижка 7', src: '/library/sale/sale7.png' },
      { name: 'Знижка 8', src: '/library/sale/sale8.png' },
      { name: 'Знижка 9', src: '/library/sale/sale9.png' },
      { name: 'Знижка 10', src: '/library/sale/sale10.png' },
      { name: 'Знижка 11', src: '/library/sale/sale11.png' },
      { name: 'Знижка 12', src: '/library/sale/sale12.png' },
      { name: 'Знижка 13', src: '/library/sale/sale13.png' },
      { name: 'Знижка 14', src: '/library/sale/sale14.png' },
      { name: 'Знижка 15', src: '/library/sale/sale15.png' },
      { name: 'Знижка 16', src: '/library/sale/sale16.png' },
      { name: 'Знижка 17', src: '/library/sale/sale17.png' },
      { name: 'Знижка 18', src: '/library/sale/sale18.png' },
      { name: 'Знижка 19', src: '/library/sale/sale19.png' },
      { name: 'Знижка 20', src: '/library/sale/sale20.png' },
      { name: 'Знижка 21', src: '/library/sale/sale21.png' },
      { name: 'Знижка 22', src: '/library/sale/sale22.png' },
      { name: 'Знижка 23', src: '/library/sale/sale23.png' },
      { name: 'Знижка 24', src: '/library/sale/sale24.png' },
      { name: 'Знижка 25', src: '/library/sale/sale25.png' },
      { name: 'Знижка 26', src: '/library/sale/sale26.png' },
      { name: 'Знижка 27', src: '/library/sale/sale27.png' },
    ],
  },
];
